09/03/2018 12:44:21 PM 	Traceback (most recent call last):
			  File "main_modulo_edit_tree.py", line 25, in main
			    args = json.loads(json_args)
			  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
			    return _default_decoder.decode(s)
			  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
			    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
			  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
			    raise ValueError(errmsg("Expecting value", s, err.value)) from None
			ValueError: Expecting value: line 1 column 1 (char 0)
			
09/03/2018 12:45:32 PM 	Traceback (most recent call last):
			  File "main_modulo_edit_tree.py", line 25, in main
			    args = json.loads(json_args)
			  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
			    return _default_decoder.decode(s)
			  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
			    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
			  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
			    raise ValueError(errmsg("Expecting value", s, err.value)) from None
			ValueError: Expecting value: line 1 column 21 (char 20)
			
09/03/2018 12:47:42 PM 	Traceback (most recent call last):
			  File "main_modulo_edit_tree.py", line 33, in main
			    namedocument = treeObj.makeJson(args['namedoc'])
			  File "/var/www/html/demo/tree_editor/clTree.py", line 160, in makeJson
			    json.dump(self.file, outfile)
			AttributeError: 'clTree' object has no attribute 'file'
			
09/03/2018 12:50:13 PM 	Traceback (most recent call last):
			  File "main_modulo_edit_tree.py", line 25, in main
			    args = json.loads(json_args)
			  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
			    return _default_decoder.decode(s)
			  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
			    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
			  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
			    raise ValueError(errmsg("Expecting value", s, err.value)) from None
			ValueError: Expecting value: line 1 column 21 (char 20)
			
09/03/2018 12:53:37 PM 	Traceback (most recent call last):
			  File "main_modulo_edit_tree.py", line 26, in main
			    args = json.loads(json_args)
			  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
			    return _default_decoder.decode(s)
			  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
			    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
			  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
			    raise ValueError(errmsg("Expecting value", s, err.value)) from None
			ValueError: Expecting value: line 1 column 21 (char 20)
			
09/03/2018 02:28:31 PM 	Traceback (most recent call last):
			  File "main_modulo_edit_tree.py", line 34, in main
			    namedocument = treeObj.makeJson(args['namedoc'])
			  File "/var/www/html/demo/tree_editor/clTree.py", line 160, in makeJson
			    json.dump(self.file, outfile)
			AttributeError: 'clTree' object has no attribute 'file'
			
09/03/2018 02:30:30 PM 	Traceback (most recent call last):
			  File "main_modulo_edit_tree.py", line 34, in main
			    namedocument = treeObj.makeJson(args['namedoc'])
			  File "/var/www/html/demo/tree_editor/clTree.py", line 160, in makeJson
			    json.dump(self.file, outfile)
			AttributeError: 'clTree' object has no attribute 'file'
			
09/03/2018 02:30:50 PM 	Traceback (most recent call last):
			  File "main_modulo_edit_tree.py", line 34, in main
			    namedocument = treeObj.makeJson(args['namedoc'])
			  File "/var/www/html/demo/tree_editor/clTree.py", line 160, in makeJson
			    json.dump(self.file, outfile)
			AttributeError: 'clTree' object has no attribute 'file'
			
09/03/2018 02:43:45 PM 	Traceback (most recent call last):
			  File "main_modulo_edit_tree.py", line 34, in main
			    answereditoreplate['doc_name'] = treeObj.makeJson(args['namedoc'])
			NameError: name 'answereditoreplate' is not defined
			
09/03/2018 04:30:21 PM 	Traceback (most recent call last):
			  File "main_modulo_edit_tree.py", line 39, in main
			    answer = makeJson(args['val'])
			NameError: name 'makeJson' is not defined
			
09/03/2018 04:31:38 PM 	Traceback (most recent call last):
			  File "main_modulo_edit_tree.py", line 39, in main
			    answer = makeJson(args['val'])
			NameError: name 'makeJson' is not defined
			
09/03/2018 04:32:31 PM 	Traceback (most recent call last):
			  File "main_modulo_edit_tree.py", line 27, in main
			    args = json.loads(json_args)
			  File "/usr/lib/python3.4/json/__init__.py", line 318, in loads
			    return _default_decoder.decode(s)
			  File "/usr/lib/python3.4/json/decoder.py", line 343, in decode
			    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
			  File "/usr/lib/python3.4/json/decoder.py", line 361, in raw_decode
			    raise ValueError(errmsg("Expecting value", s, err.value)) from None
			ValueError: Expecting value: line 1 column 36 (char 35)
			
09/03/2018 04:33:21 PM 	Traceback (most recent call last):
			  File "main_modulo_edit_tree.py", line 39, in main
			    answer = makeJson(args['val'])
			NameError: name 'makeJson' is not defined
			
09/03/2018 04:33:37 PM 	Traceback (most recent call last):
			  File "main_modulo_edit_tree.py", line 39, in main
			    answer = makeJson(args['val'])
			NameError: name 'makeJson' is not defined
			
09/03/2018 04:35:20 PM 	Traceback (most recent call last):
			  File "main_modulo_edit_tree.py", line 39, in main
			    answer = makeJson(args['val'])
			NameError: name 'makeJson' is not defined
			
09/03/2018 04:38:28 PM 	Traceback (most recent call last):
			  File "main_modulo_edit_tree.py", line 39, in main
			    answer = makeJson(args['val'])
			NameError: name 'makeJson' is not defined
			
09/03/2018 04:39:32 PM 	Traceback (most recent call last):
			  File "main_modulo_edit_tree.py", line 40, in main
			    answer = makeJson(args['val'])
			NameError: name 'makeJson' is not defined
			
09/03/2018 04:41:17 PM 	Traceback (most recent call last):
			  File "main_modulo_edit_tree.py", line 40, in main
			    answer = makeJson(args['val'])
			NameError: name 'makeJson' is not defined
			
09/03/2018 04:42:02 PM 	Traceback (most recent call last):
			  File "main_modulo_edit_tree.py", line 40, in main
			    answer = makeJson(args['val'])
			NameError: name 'makeJson' is not defined
			
09/03/2018 04:42:32 PM 	Traceback (most recent call last):
			  File "main_modulo_edit_tree.py", line 40, in main
			    answer = makeJson(args['val'])
			NameError: name 'makeJson' is not defined
			
